# Generated by Django 3.2.9 on 2022-06-23 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"verbose_name": "Ответ", "verbose_name_plural": "Ответы"},
        ),
        migrations.AlterModelOptions(
            name="colorobjects",
            options={"verbose_name": "Массив цветов"},
        ),
    ]
